osx_image: xcode8

language:  objective-c

branches:
  only:
  - develop

before_install:
- rvm get head
- brew update
- brew outdated carthage || brew upgrade carthage
- gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet

script:
- travis_retry xcodebuild -project MYUtils.xcodeproj -target MYUtils-iOS 	 -destination "platform=iOS Simulator,name=iPhone 6,OS=10.0"
- travis_retry xcodebuild -project MYUtils.xcodeproj -target MYUtils-macOS
- travis_retry xcodebuild -project MYUtils.xcodeproj -target MYJSON-tvOS     -destination "platform=tvOS Simulator,name=Apple TV 1080p"
- travis_retry xcodebuild -project MYUtils.xcodeproj -target MYUtils-watchOS -destination "platform=watchOS Simulator,name=Apple Watch Series 2 - 42mm"
- pod lib lint --quick
- carthage build --no-skip-current